version: "2.1"

services:
  kolibri:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "kolibri_home:/root/.kolibri"

volumes:
  kolibri_home:
